[package]
name = "teximex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
regex = "1.10.2"
resvg = "0.25.0"
#tectonic = "0.13"
tiny-skia = "0.8.2"
usvg = "0.25.0"
